# Generated by Django 4.2.5 on 2023-10-01 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_string_id_alter_string_english"),
    ]

    operations = [
        migrations.CreateModel(
            name="DJ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("picture", models.BooleanField()),
                ("booking_url", models.CharField(max_length=200, null=True)),
                ("soundcloud_url", models.CharField(max_length=200, null=True)),
                ("rate", models.IntegerField()),
                ("user", models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
