# Generated by Django 4.2.5 on 2023-10-06 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("app", "0004_dj"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ("region", models.CharField(choices=[("us", "United States"), ("australia", "Australia"), ("europe", "Europe")], max_length=100)),
                ("account_holder", models.CharField(max_length=500)),
                ("bsb", models.CharField(max_length=20, null=True)),
                ("ach", models.CharField(max_length=100, null=True)),
                ("account_type", models.CharField(choices=[("checking", "Checking"), ("savings", "Savings")], max_length=20, null=True)),
                ("account_number", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
