# Generated by Django 4.2.5 on 2023-10-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_dj_rate_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="checkout_session_id",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
