# Generated by Django 4.2.5 on 2023-10-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_booking_checkout_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="language",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.language"),
        ),
    ]
