# Generated by Django 4.2.5 on 2023-10-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_booking_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dj",
            name="picture",
            field=models.IntegerField(null=True),
        ),
    ]
